apiVersion: v1
kind: Service
metadata:
  name: image-resizer
  labels:
    app: image-resizer
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: image-resizer
    tier: frontend
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: image-resizer
  labels:
    app: image-resizer
    tier: frontend
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: image-resizer
        tier: frontend
    spec:
      containers:
      - name: image-resizer
        image: aseovic/image-resizer:0.1.0
        resources:
          requests:
            cpu: 100m
            memory: 1000Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 3000

